%YAML:1.0

#--------------------------------------------------------------------------------------------
# System Control
#--------------------------------------------------------------------------------------------

# Number of threads used for optimization routines
sys.threads_server: 8

sys.covis_thres: 10 # Threshold for min. number of shared edges to include a covisibility edge

#--------------------------------------------------------------------------------------------
# Data input
#--------------------------------------------------------------------------------------------

# maps are loaded from here (use absolute path)
sys.map_path0: '/home/pschmuck/ws/covins_ws/src/covins/covins_backend/output/map_data'

# Format for the trajectory output file
sys.trajectory_format: 'TUM' # {EUROC|TUM}
# EUROC: EuRoC format - stamp[ns], tx, ty, tz, qw, qx, qy, qz
# TUM: TUM format - stamp[s] tx ty tz qx qy qz qw

#--------------------------------------------------------------------------------------------
# Features
#--------------------------------------------------------------------------------------------

feat.type: 'ORB' # this allows to integrate other PR algorithms. Cuurently, only 'ORB' is supported
feat.desc_length: 32 # [Byte] COVINS-ORB: 32

feat.num_octaves: 1 # Number of levels in the scale pyramid
feat.scale_factor: 2.0 # Scale factor between levels in the scale pyramid

#--------------------------------------------------------------------------------------------
# Feature Matching
#--------------------------------------------------------------------------------------------

matcher.desc_matching_th_low: 50
matcher.desc_matching_th_high: 100

matcher.search_radius_SE3: 9.5
matcher.search_radius_proj: 10.0
matcher.search_radius_fuse: 10.0

#--------------------------------------------------------------------------------------------
# Mapping
#--------------------------------------------------------------------------------------------

mapping.activate_lm_culling: 1

mapping.kf_culling_th_red: 0.95 # redundancy threshold for callback
mapping.kf_culling_max_time_dist: 1.0 #s - max. allowed time distance between 2 consecutive KFs. Constraint for redundancy removal

#--------------------------------------------------------------------------------------------
# Place Recognition Parameters
#--------------------------------------------------------------------------------------------

# activate / deactivate place recognition
placerec.active: 1

placerec.type: 'COVINS' # this allows to integrate other PR algorithms. Currently, only 'COVINS' is supported

placerec.start_after_kf: 10 # map matching skips the first x KFs after map initialization
placerec.consecutive_loop_dist: 10 # after finding a loop, the next x KFs are not considered loop closure query
placerec.min_loop_dist: 10 # minimum number of KFs between the two ends of the loop to accept loop
placerec.cov_consistency_thres: 3

placerec.solver_iterations: 5
placerec.matches_thres: 20
placerec.matches_thres_merge: 20
placerec.inliers_thres: 20

placerec.total_matches_thres: 40

placerec.ransac.min_inliers: 6
placerec.ransac.probability: 0.99
placerec.ransac.max_iterations: 300
placerec.ransac.class_threshold: 25

placerec.exclude_kfs_with_id_less_than: 10
placerec.inter_map_matches_only: 0

#--------------------------------------------------------------------------------------------
# Optimization
#--------------------------------------------------------------------------------------------

opt.pgo_iteration_limit: 20 # PGO max iterations

opt.gba_iteration_limit: 10 # GBA max iterations
opt.gba_use_map_loop_constraints: 1

opt.th_outlier_align: 1.3
opt.th_gba_outlier_global: 0.92

opt.perform_pgo: 1
opt.pgo_fix_kfs_after_gba: 1 #KFs that were part of a GBA are fixed in future PGO runs
opt.pgo_fix_poses_loaded_maps: 0
opt.gba_fix_poses_loaded_maps: 0

#--------------------------------------------------------------------------------------------
# Visualization
#--------------------------------------------------------------------------------------------

vis.active: 1 # activate / deactivate visualization

# activate different visualization items
vis.showcovgraph: 1
vis.showlandmarks: 1
vis.showtraj: 1
vis.showkeyframes: 1

vis.covgraph_minweight: 10 # min. weight of covisibility edges to be displayed
vis.covgraph_shared_edges_only: 1 # only display covisibility edges between trajectories from different agents

vis.scalefactor: 1.0 # scale the visalized map by this factor

# ROS marker sizes
vis.trajmarkersize: 0.05
vis.covmarkersize: 0.008
vis.loopmarkersize: 0.04
vis.camsize: 0.1
vis.camlinesize: 0.01

# Colors for agents
vis.colorR0: 0.55
vis.colorG0: 0.83
vis.colorB0: 0.78

vis.colorR1: 1.00
vis.colorG1: 1.00
vis.colorB1: 0.70

vis.colorR2: 0.75
vis.colorG2: 0.73
vis.colorB2: 0.85

vis.colorR3: 0.98
vis.colorG3: 0.50
vis.colorB3: 0.45

vis.colorR4: 0.50
vis.colorG4: 0.69
vis.colorB4: 0.83

vis.colorR5: 0.99
vis.colorG5: 0.71
vis.colorB5: 0.38

vis.colorR6: 0.70
vis.colorG6: 0.87
vis.colorB6: 0.41

vis.colorR7: 0.99
vis.colorG7: 0.80
vis.colorB7: 0.90

vis.colorR8: 0.85
vis.colorG8: 0.85
vis.colorB8: 0.85

vis.colorR9: 0.74
vis.colorG9: 0.50
vis.colorB9: 0.74

vis.colorR10: 0.80
vis.colorG10: 0.92
vis.colorB10: 0.77

vis.colorR11: 1.00
vis.colorG11: 0.93
vis.colorB11: 0.44

# Colors for covisibility graph edges
vis.colorRcov: 0.6
vis.colorGcov: 0.6
vis.colorBcov: 0.6
